### ISSUE TITLE
how to get the gz format file

### ISSUE THREAD

**Issue by huangl07** [shubhamchandak94/Spring#10]
My dear

thank you for excellent software for compress，but when I was using your package，was there no way to get a fastq.gz decompress file? 

may you patched it for decompress output?

thankyou!

**Comment by shubhamchandak94** [comment]
Do you mean an option to produce a gzipped file during decompression?

**Comment by huangl07** [comment]
yeah!

I think most of software could read gziped fastq file. so there maybe not neccessary need for txt fastq file.

**Comment by shubhamchandak94** [comment]
I see. Thanks for the suggestion. I'll add this feature next week and let you know once done.
Shubham

**Comment by shubhamchandak94** [comment]
I have now added the option. By specifying the -g flag during decompression, the output is written to gzipped fastq files.
```
./spring -d -i compressedfilename -o file_1.fastq.gz file_2.fastq.gz -g
```
Note that this can make the decompression a bit slower because of the added gzip compression step (it is parallelized so it's not too bad). It reduces the I/O but increases the compute, and of course can be a good option if disk space is an issue.
