### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by leonschuetz** [shubhamchandak94/Spring#13]
Hi,
I tested your tool on whole genome FASTQ files and the result seems quite promising. But a major drawback is the high memory consumption. It needed for a 160GB gzipped input around 128GB of RAM. Is this amount of memory expected and if so is there any way to reduce it?

Best Regards,
Leon

**Comment by shubhamchandak94** [comment]
Hi Leon,
You are right, the compression memory is a drawback of the current compression framework. As you'll notice, this problem is common to a lot of other FASTQ compressors that perform significantly better than the off-the-shelf tools like gzip.
In case of SPRING, the reason for this high memory consumption is the fact that SPRING attempts to perform an approximate assembly from the reads and loads all the reads into RAM for this purpose. Making something like this work without using RAM and relying on the disk and temporary files is an interesting challenge (and would be a whole new compressor). [Orcom](http://sun.aei.polsl.pl/REFRESH/index.php?page=projects&project=orcom&subpage=about) is one of the only compressors I know that does something on those lines, but it only works with read sequences (not the full FASTQ) and does not support paired end data. I am confident that sooner or later someone will come up with an answer.
In the short term, one idea to handle this could be to split the file into (say) 2 parts and compress them independently with SPRING. That would reduce the memory consumption to half and the increase in the total compressed size will be something like 1 to 2 GB (for WGS human data). Since many times the original fastq files represent one lane or one run, you can just work with these and might not need to split the fastq file into smaller parts. We played around with this idea a little bit in the [HARC paper](https://academic.oup.com/bioinformatics/article/34/4/558/4386919) (see end of paper), where HARC is the predecessor of SPRING.
Regards,
Shubham

**Comment by leonschuetz** [comment]
Hi Shubham,
Thank you for your answer. Your explanation make sense, so I will try to use the individual lanes. I only concatenated the fastq files, so I can improve the compression.

Best Regards,
Leon
