### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by jvolkening** [shubhamchandak94/Spring#20]
After installing from conda (bioconda), I am unable to run Spring. Any calls to the command die with 'Illegal instruction', which suggests a compiler incompatibility. I am on an x86-64 system running Debian buster. I am able to clone from git, build, and run the resulting binary without problems.

**Comment by shubhamchandak94** [comment]
Thanks for pointing this out. I think this is an issue with the machine architecture. The default compilation done by bioconda ([build script here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/spring/build.sh)) seems to assume certain instructions that might not be present in your machine. Possibly the AVX/AVX2 instructions. It seems to work without issues on the linux machines I tested with. 
On the other hand, when you compile with the clone, it just uses -march=native which makes use of the current machine architecture.
From what I understand, the default bioconda flags should work on most machines. So I don't know if specifying my own flags is a good idea. Perhaps the best option is to add a comment on the README saying that if you get such an error, please compile from source. Let me know if you think otherwise.

**Comment by shubhamchandak94** [comment]
Actually it seems it fails on one machine on my end as well! I will try to change the compilation flags and let you know

**Comment by jvolkening** [comment]
Thanks for the quick reply. If it helps, I tested on my laptop:

Intel(R) Core(TM) i7-3520M: **FAILED**

on another development box here:

AMD Phenom(tm) II X4 910e: **FAILED**

and on an EC2 instance:

Intel(R) Xeon(R) Platinum 8259CL: **WORKED**

I use conda daily on all of these platforms and don't remember running into this issue before.

**Comment by shubhamchandak94** [comment]
Can you try again (version 1.0.1)? I changed the compile flag for bioconda.

**Comment by shubhamchandak94** [comment]
I think it will still not work for the AMD because it doesn't support SSE 4.1 instructions. I will just remove any hardware specific optimizations for bioconda and let you know once that's done

**Comment by jvolkening** [comment]
Appears to be working now with 1.0.1. At least, it doesn't immediately die -- I haven't tried on real data yet.

Thanks! We are looking for a FASTQ compression tool for archival storage, but so many promising projects seem to be inactive with years-old unresolved bugs. Spring has given good results in testing so far, and I hope that it stays active!

**Comment by shubhamchandak94** [comment]
That's great! Can you verify that it works on the AMD box?

**Comment by jvolkening** [comment]
> I think it will still not work for the AMD (Phenom II)

Correct -- still not working on the AMD Phenom II box, using conda build spring-1.0.1-he513fc3_0.

FWIW, I just also tested on an EC2 m5a instance with AMD EPYC 7571 processors, and that worked. The AMD Phenom II box is an older architecture, so if you don't want to spend time trying to support it, I would understand. Personally, I would mostly be using Spring on EC2.

**Comment by shubhamchandak94** [comment]
Got it, then I'll leave it as is for now and add an explanatory comment in the README.
