### ISSUE TITLE
MD5 hash mismatch observed in compressed/decompressed files with Spring

### ISSUE THREAD

**Issue by xec-cm** [shubhamchandak94/Spring#30]
### Description

I'm using Spring for compression and decompression of my FASTQ files. However, I'm experiencing an issue where the hash of the compressed and decompressed files in the first iteration is different from the hash of the original file. After the first iteration, the hashes of the compressed and decompressed files are the same.

### Reproducible Code

[1_sample2_R1.fastq.gz](https://github.com/shubhamchandak94/Spring/files/10924949/1_sample2_R1.fastq.gz)

```bash
fastq_1="sample2_R1.fastq.gz"
prefix=${fastq_1%%.fastq.gz}

for i in {1..5}
do 
    it=$((i + 1)) 
    spring -c -g -i ${i}_${prefix}.fastq.gz -o ${i}_${prefix}.spring
    spring -d -g -i ${i}_${prefix}.spring -o ${it}_${prefix}.fastq.gz

    input_md5=`md5sum ${i}_${prefix}.fastq.gz | cut -d' ' -f1`
    output_md5=`md5sum ${it}_${prefix}.fastq.gz | cut -d' ' -f1`

    echo "iteration ${i} input: $input_md5 output: $output_md5" >> results.txt
done

cat results.txt
```

### Result

    iteration 1 input: 43df7c96f72f02ba601458b742a7b57c output: c3a55c1ec9987fbbba73744ed2b214ac
    iteration 2 input: c3a55c1ec9987fbbba73744ed2b214ac output: c3a55c1ec9987fbbba73744ed2b214ac
    iteration 3 input: c3a55c1ec9987fbbba73744ed2b214ac output: c3a55c1ec9987fbbba73744ed2b214ac
    iteration 4 input: c3a55c1ec9987fbbba73744ed2b214ac output: c3a55c1ec9987fbbba73744ed2b214ac
    iteration 5 input: c3a55c1ec9987fbbba73744ed2b214ac output: c3a55c1ec9987fbbba73744ed2b214ac

### Expected Output

I expect the hash of the compressed and decompressed files to match the hash of the original file for all iterations.

### Observed Output

In the first iteration, the hash of the compressed file is 43df7c96f72f02ba601458b742a7b57c and the hash of the decompressed file is c3a55c1ec9987fbbba73744ed2b214ac. However, in all subsequent iterations, the hash of the compressed and decompressed files match and are c3a55c1ec9987fbbba73744ed2b214ac.

### Questions

Can you provide any insight into what may be causing this issue and if there are any potential solutions or workarounds?

Thanks

**Comment by shubhamchandak94** [comment]
Are you computing the hash of the gzipped files? Spring does not make a promise about recovering the same gzip file bit by bit since since there are several gzipped files corresponding to the same raw file (e.g., generated using different levels or versions of the encoder). It is hard but not impossible to get the same gzip back but it’s not in the spring roadmap to support that. 

The reason that the hash starts matching after the first run is that the spring decoder always applies gzip in the same exact way. 

The hash of the input fastq (not fastq.gz) and the decompressed should match (even for this if your input has windows line endings the files might differ since spring produces Linux line endings on decompression. You can check this hash by piping the file via gunzip or zcat.

**Comment by shubhamchandak94** [comment]
Closing this issue, please reopen if you have any further comments.
