### ISSUE TITLE
How to read .spring compressed file

### ISSUE THREAD

**Issue by shri1984** [shubhamchandak94/Spring#38]
Hi Shubham, 
Thanks for the fantastic tool. Superb!!!
 Can you suggest a tool such as vi to quickly peek through the .spring formatted file after compression of paired end reads? 

Shripathi

**Comment by shubhamchandak94** [comment]
Hi Shripathi,
Thanks for the question and sorry for the delayed response. Spring just not have a format that's conducive to streaming due to my own lack of knowledge 6 years ago. There are a few options you could consider:
1. Use the range decompression functionality in spring like 
```
./spring -d -i file.spring -o file_1.fastq file_2.fastq --decompress-range 0 1000
```
This will decompress the first 1000 pairs and will run faster than decompressing the whole file.
2. Use named pipes instead of files which will allow you to then pass on the named pipe to whatever tool or vim. I'm not 100% sure if Spring will clean up the temporary directories after the pipe breaks, so that's something to watch out for and clean up yourself.

Note that in both these options there is some fixed overhead of untarring the archive and decompressing the assembled sequence, after which Spring would only decompress as much as desired.

**Comment by shri1984** [comment]
Thank you Shubham.
