### ISSUE TITLE
build issues on Ubuntu 1604

### ISSUE THREAD

**Issue by colindaven** [shubhamchandak94/Spring#8]
Hi, saw your nice talk at ISMB.

On an Ubuntu 1604 cluster, I can't build the software because the cmake is too old. Fine.

Unfortunately, I can't make cmake via the workaround either (!).

Although libssl-dev is present, I get an error
cmake-3.12.1$ sudo apt install libssl-dev

./configure
make -j 8

error:
fatal error: openssl/hmac.h: No such file or directory

The solution for this error seems to be installing libssl-dev, which is installed.

Do you recommend I go to an earlier cmake, eg 3.10 ?

Or are you planning to build releases for eg Ubuntu 1604 ?

Thanks,
Colin

**Comment by shubhamchandak94** [comment]
Hi Colin,
Thanks for trying out SPRING. I tried to build spring using cmake-3.10.3 and cmake-3.9.6 and it works fine in both cases (albeit on Ubuntu 18.04.1). To do this you can just replace the cmake-3.12.1 in the instruction with cmake-3.10.3 or cmake-3.9.6. Can you see if any of these work? In that case I will update the README with the earliest version that works. Otherwise, can you send me the error you get.
Versions before 3.9 will likely not work because of boost-cmake dependency. 
Thanks,
Shubham

**Comment by colindaven** [comment]
Hi Shubham,

thanks for your help and the clear instructions.

For Ubuntu 1604, downloading the source (not the precompiled Linux 64 version, which I did by mistake initially) of 
`cmake-3.10.3`
compiling this, and using it to compile SPRING was successful so far.
```
/mnt/ngsnfs/tools/SPRING/build$ ./spring 
Exactly one of compress or decompress needs to be specified 
Allowed options:
  -h [ --help ]                   produce help message
```

Thanks for your help
Colin
